export const classes = [
  {
    day: 1,
    time: '12:00',
    duration: 60,
    name: 'Pilates kõigile',
    instructor: 'Erika',
  },
  { day: 1, time: '17:00', duration: 60, name: 'Tower', instructor: 'Erika' },
  { day: 2, time: '10:00', duration: 60, name: 'Tower', instructor: 'Erika' },
  {
    day: 2,
    time: '16:30',
    duration: 60,
    name: 'L1 / L2',
    instructor: 'Erika',
  },
  { day: 2, time: '17:30', duration: 60, name: 'L1', instructor: 'Erika' },
  {
    day: 3,
    time: '12:00',
    duration: 60,
    name: 'Pilates kõigile',
    instructor: 'Erika',
  },
  { day: 3, time: '17:00', duration: 60, name: 'Tower', instructor: 'Erika' },
  {
    day: 3,
    time: '18:00',
    duration: 60,
    name: 'L1',
    instructor: 'Erika',
  },
  {
    day: 4,
    time: '08:15',
    duration: 60,
    name: 'Võimleme koos',
    instructor: 'Erika',
  },
  {
    day: 4,
    time: '10:00',
    duration: 60,
    name: 'Baas / L1',
    instructor: 'Erika',
  },
  { day: 4, time: '16:30', duration: 60, name: 'L2', instructor: 'Erika' },
  { day: 4, time: '17:30', duration: 60, name: 'L1', instructor: 'Erika' },
  { day: 5, time: '10:00', duration: 60, name: 'Tower', instructor: 'Erika' },
  {
    day: 5,
    time: '11:30',
    duration: 60,
    name: 'Yin jooga',
    instructor: 'Erika',
  },
  { day: 7, time: '10:00', duration: 60, name: 'L1', instructor: 'Erika' },
  {
    day: 7,
    time: '11:00',
    duration: 60,
    name: 'START-tund (alates 14.09)',
    instructor: 'Erika',
  },
];
